# 1.NLP for feature extraction

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import nltk as nk
%matplotlib inline

In [2]:
data = pd.read_csv('jobs_data.csv' )

In [3]:
data.tail()

Unnamed: 0                                              title  \
10865       10865                                     Odoo Developer   
10866       10866                  Senior PHP Developer - Alexandria   
10867       10867  Sales & Account Manager (Real Estate / Medical...   
10868       10868  Technical and Network Support Engineer - Alexa...   
10869       10869                              Senior Java Developer   

                                             jobFunction  \
10865  ['IT/Software Development', 'Engineering - Tel...   
10866  ['Engineering - Telecom/Technology', 'IT/Softw...   
10867  ['Business Development', 'Sales/Retail', 'Cust...   
10868  ['Installation/Maintenance/Repair', 'Engineeri...   
10869  ['IT/Software Development', 'Engineering - Tel...   

                                                industry  
10865  ['Real Estate/Property Management', 'Manufactu...  
10866                ['Information Technology Services']  
10867  ['Real Estate/Property Management', 'Retail', ...  
10868  ['Computer Software', 'Education', 'Healthcare...  
10869                ['Information Technology Services']

In [4]:
data['ID'] = data.iloc[:,0]

In [5]:
data = data[['ID','title','jobFunction','industry']]

In [6]:
data.head()

ID                                    title  \
0   0                 Full Stack PHP Developer   
1   1  CISCO Collaboration Specialist Engineer   
2   2            Senior Back End-PHP Developer   
3   3                              UX Designer   
4   4                      Java Technical Lead   

                                         jobFunction  \
0  ['Engineering - Telecom/Technology', 'IT/Softw...   
1  ['Installation/Maintenance/Repair', 'IT/Softwa...   
2  ['Engineering - Telecom/Technology', 'IT/Softw...   
3  ['Creative/Design/Art', 'IT/Software Developme...   
4  ['Engineering - Telecom/Technology', 'IT/Softw...   

                                            industry  
0  ['Computer Software', 'Marketing and Advertisi...  
1                ['Information Technology Services']  
2       ['Computer Software', 'Computer Networking']  
3  ['Computer Software', 'Information Technology ...  
4  ['Computer Software', 'Information Technology ...

In [7]:
data.shape

(10870, 4)

In [8]:
data['title']

0                                 Full Stack PHP Developer
1                  CISCO Collaboration Specialist Engineer
2                            Senior Back End-PHP Developer
3                                              UX Designer
4                                      Java Technical Lead
                               ...                        
10865                                       Odoo Developer
10866                    Senior PHP Developer - Alexandria
10867    Sales & Account Manager (Real Estate / Medical...
10868    Technical and Network Support Engineer - Alexa...
10869                                Senior Java Developer
Name: title, Length: 10870, dtype: object

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10870 entries, 0 to 10869
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   ID           10870 non-null  int64 
 1   title        10870 non-null  object
 2   jobFunction  10870 non-null  object
 3   industry     10870 non-null  object
dtypes: int64(1), object(3)
memory usage: 339.8+ KB


No Missing Values

In [10]:
data.describe().transpose()

count    mean          std  min      25%     50%      75%      max
ID  10870.0  5434.5  3138.043047  0.0  2717.25  5434.5  8151.75  10869.0

In [11]:
data['tit_ind'] = data['title'] + data['industry']  

In [12]:
data['tit_ind'].head()

0    Full Stack PHP Developer['Computer Software', ...
1    CISCO Collaboration Specialist Engineer['Infor...
2    Senior Back End-PHP Developer['Computer Softwa...
3    UX Designer['Computer Software', 'Information ...
4    Java Technical Lead['Computer Software', 'Info...
Name: tit_ind, dtype: object

In [13]:
import re

In [14]:
from nltk.corpus import stopwords
from nltk.corpus import words
from nltk.stem.porter import PorterStemmer
#nltk.download('stopwords')
#nltk.download('words')

In [15]:
corpus = []
for i in range(0, len(data['tit_ind'])):
    jobtitle = re.sub('[^a-zA-Z]', ' ', data['tit_ind'][i])
    jobtitle = jobtitle.lower()
    jobtitle = jobtitle.split()
    ps = PorterStemmer()
    jobtitle = [ps.stem(word) for word in jobtitle if not word in set(stopwords.words('english'))] # this will also remove arabic word
    jobtitle = ' '.join(jobtitle)
    corpus.append(jobtitle)

In [16]:
corpus 

['full stack php develop comput softwar market advertis',
 'cisco collabor specialist engin inform technolog servic',
 'senior back end php develop comput softwar comput network',
 'ux design comput softwar inform technolog servic comput game',
 'java technic lead comput softwar inform technolog servic',
 'technic support engin inform technolog servic comput softwar',
 'senior io develop inform technolog servic graphic design comput softwar',
 'mechan engin architectur design servic engin servic construct residenti commerci offic',
 'real estat sale specialist th ramadan real estat properti manag',
 'school princip educ',
 'senior sale repres market advertis',
 'account educ',
 'indoor sale execut architectur design servic manufactur furnitur',
 'php full stack joomla expert inform technolog servic',
 'english teacher assist educ',
 'market coordin market advertis',
 'senior busi develop market advertis comput softwar public relat commun',
 'senior websit develop insur comput softwar',

In [17]:
data['function'] = data['jobFunction'] + data['industry'] 

In [18]:
corpus_2 = []
for i in range(0, len(data['function'])):
    jobfunction = re.sub('[^a-zA-Z]', ' ', data['function'][i])
    jobfunction = jobfunction.lower()
    jobfunction = jobfunction.split()
    ps = PorterStemmer()
    jobfunction = [ps.stem(word) for word in jobfunction if not word in set(stopwords.words('english'))] # this will also remove arabic word
    jobfunction = ' '.join(jobfunction)
    corpus_2.append(jobfunction)

In [19]:
corpus_2 

['engin telecom technolog softwar develop comput softwar market advertis',
 'instal mainten repair softwar develop engin telecom technolog inform technolog servic',
 'engin telecom technolog softwar develop comput softwar comput network',
 'creativ design art softwar develop comput softwar inform technolog servic comput game',
 'engin telecom technolog softwar develop comput softwar inform technolog servic',
 'softwar develop engin telecom technolog custom servic support inform technolog servic comput softwar',
 'engin telecom technolog softwar develop inform technolog servic graphic design comput softwar',
 'engin mechan electr architectur design servic engin servic construct residenti commerci offic',
 'sale retail real estat properti manag',
 'educ teach administr oper manag educ',
 'sale retail market pr advertis media journal publish market advertis',
 'account financ educ',
 'sale retail creativ design art architectur design servic manufactur furnitur',
 'softwar develop engin te

In [20]:
d = {'ID': data['ID'] ,'job': corpus}

In [21]:
df_job = pd.DataFrame(data = d)

In [22]:
df_job.head()

ID                                                job
0   0  full stack php develop comput softwar market a...
1   1  cisco collabor specialist engin inform technol...
2   2  senior back end php develop comput softwar com...
3   3  ux design comput softwar inform technolog serv...
4   4  java technic lead comput softwar inform techno...

In [23]:
df_func = pd.DataFrame({'function' :corpus_2})

In [24]:
df_func.head()

function
0  engin telecom technolog softwar develop comput...
1  instal mainten repair softwar develop engin te...
2  engin telecom technolog softwar develop comput...
3  creativ design art softwar develop comput soft...
4  engin telecom technolog softwar develop comput...

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
tfidf_job = tf.fit_transform(df_job.iloc[:,1])
tfidf_func = tf.transform(df_func.iloc[:,0])

In [26]:
tfidf_func.shape

(10870, 1166)

In [27]:

from sklearn.metrics.pairwise import cosine_similarity

cos_similarity_tfidf = map(lambda x: cosine_similarity(tfidf_job,x), tfidf_func )

In [28]:
cosine_similarity(tfidf_job,tfidf_func)

array([[0.31427975, 0.07654005, 0.20780143, ..., 0.03956276, 0.12458076,
        0.1067476 ],
       [0.08416197, 0.12207032, 0.07939854, ..., 0.02570602, 0.07183958,
        0.170247  ],
       [0.19465204, 0.06763879, 0.37387165, ..., 0.03496179, 0.13441347,
        0.09433334],
       ...,
       [0.        , 0.01098273, 0.        , ..., 0.63691845, 0.16549286,
        0.01531721],
       [0.16327297, 0.08966696, 0.30442442, ..., 0.29879118, 0.35178467,
        0.12505522],
       [0.13257027, 0.20386998, 0.12506701, ..., 0.0987395 , 0.11589223,
        0.28432998]])

In [29]:
output2 = list(cos_similarity_tfidf)

In [30]:
output2 

[array([[0.31427975],
        [0.08416197],
        [0.19465204],
        ...,
        [0.        ],
        [0.16327297],
        [0.13257027]]),
 array([[0.07654005],
        [0.12207032],
        [0.06763879],
        ...,
        [0.01098273],
        [0.08966696],
        [0.20386998]]),
 array([[0.20780143],
        [0.07939854],
        [0.37387165],
        ...,
        [0.        ],
        [0.30442442],
        [0.12506701]]),
 array([[0.17616266],
        [0.06134351],
        [0.21201196],
        ...,
        [0.011575  ],
        [0.12547815],
        [0.1745394 ]]),
 array([[0.17697719],
        [0.1578007 ],
        [0.19094537],
        ...,
        [0.01419741],
        [0.18196521],
        [0.26354338]]),
 array([[0.14575895],
        [0.14602104],
        [0.15726319],
        ...,
        [0.02338606],
        [0.31794818],
        [0.24554243]]),
 array([[0.15907808],
        [0.14184106],
        [0.17163355],
        ...,
        [0.01276151],
        [0.163561

In [31]:
def get_recommendation(jobtitle):
    #recommendation = pd.DataFrame(columns = ['ID','title' , 'Recommended function', 'score'])
    id = list(data['title']).index(jobtitle)
    recommended = data['jobFunction'][id]
    score = output2[id][0][0]
    result = {'ID': id , 'title':jobtitle ,'Recommended function' : recommended , 'score':score  }
    result = pd.DataFrame(result , index = range(1))
    return result

In [32]:
get_recommendation('Odoo Developer')

ID           title                               Recommended function  \
0  223  Odoo Developer  ['Engineering - Telecom/Technology', 'IT/Softw...   

      score  
0  0.208842